// Code generated by protoc-gen-rest-metadata. DO NOT EDIT.
// source: stateservice.proto

/*
Package lnrpc contains REST metadata.
*/
package lnrpc

import (
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
)

// RegisterStateHandlerMetadata registers the http
// handler metadata for service State.
func RegisterStateHandlerMetadata(targetMap map[string]struct {
	ClientStreaming bool
	ServerStreaming bool
	Method          string
	Pattern         runtime.Pattern
}) {

	targetMap["/lnrpc.State/SubscribeState"] = struct {
		ClientStreaming bool
		ServerStreaming bool
		Method          string
		Pattern         runtime.Pattern
	}{
		ClientStreaming: false,
		ServerStreaming: true,
		Method:          "GET",
		Pattern:         runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v1", "state", "subscribe"}, "", runtime.AssumeColonVerbOpt(true))),
	}

	targetMap["/lnrpc.State/GetState"] = struct {
		ClientStreaming bool
		ServerStreaming bool
		Method          string
		Pattern         runtime.Pattern
	}{
		ClientStreaming: false,
		ServerStreaming: false,
		Method:          "GET",
		Pattern:         runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"v1", "state"}, "", runtime.AssumeColonVerbOpt(true))),
	}

}
