// Code generated by protoc-gen-rest-metadata. DO NOT EDIT.
// source: verrpc/verrpc.proto

/*
Package verrpc contains REST metadata.
*/
package verrpc

import (
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
)

// RegisterVersionerHandlerMetadata registers the http
// handler metadata for service Versioner.
func RegisterVersionerHandlerMetadata(targetMap map[string]struct {
	ClientStreaming bool
	ServerStreaming bool
	Method          string
	Pattern         runtime.Pattern
}) {

	targetMap["/verrpc.Versioner/GetVersion"] = struct {
		ClientStreaming bool
		ServerStreaming bool
		Method          string
		Pattern         runtime.Pattern
	}{
		ClientStreaming: false,
		ServerStreaming: false,
		Method:          "GET",
		Pattern:         runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v2", "versioner", "version"}, "", runtime.AssumeColonVerbOpt(true))),
	}

}
