// Code generated by protoc-gen-rest-metadata. DO NOT EDIT.
// source: watchtowerrpc/watchtower.proto

/*
Package watchtowerrpc contains REST metadata.
*/
package watchtowerrpc

import (
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
)

// RegisterWatchtowerHandlerMetadata registers the http
// handler metadata for service Watchtower.
func RegisterWatchtowerHandlerMetadata(targetMap map[string]struct {
	ClientStreaming bool
	ServerStreaming bool
	Method          string
	Pattern         runtime.Pattern
}) {

	targetMap["/watchtowerrpc.Watchtower/GetInfo"] = struct {
		ClientStreaming bool
		ServerStreaming bool
		Method          string
		Pattern         runtime.Pattern
	}{
		ClientStreaming: false,
		ServerStreaming: false,
		Method:          "GET",
		Pattern:         runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v2", "watchtower", "server"}, "", runtime.AssumeColonVerbOpt(true))),
	}

}
